/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.retrylife.pureviz;

import java.awt.Color;

import PicoEngine.Window;

public class App implements Runnable {

    // GUI
    private Window window;

    public static void main(String[] args) {
        new App().run();
    }

    App() {

        // Set up the window
        window = new Window(800, 600, 100, 100, "PureViz");
        window.autoConfig(Color.white);
    }

    @Override
    public void run() {

    }
}
